import type { EntryMeta, GalleryGroup } from './types';

const BUTTON_VARIANTS = ['default', 'secondary', 'destructive', 'outline', 'ghost', 'link'];
const BUTTON_SIZES = ['default', 'sm', 'lg', 'icon'];

/**
 * Every gallery entry's metadata. The render component for `slug` lives in
 * `renders.tsx`. Keep this list and that map in sync — a new component's
 * definition of done includes an entry in both.
 */
export const entriesMeta: EntryMeta[] = [
	// ---- @watts/ui primitives ------------------------------------------------
	{
		slug: 'ui/button',
		name: 'Button',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/button',
		controls: [
			{ name: 'children', type: 'text', default: 'Get involved' },
			{ name: 'variant', type: 'select', options: BUTTON_VARIANTS, default: 'default' },
			{ name: 'size', type: 'select', options: BUTTON_SIZES, default: 'default' },
			{ name: 'disabled', type: 'boolean', default: false },
		],
		variants: BUTTON_VARIANTS.map((v) => ({ name: v, props: { variant: v } })),
	},
	{
		slug: 'ui/card',
		name: 'Card',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/card',
		controls: [
			{ name: 'title', type: 'text', default: 'General Body Meeting' },
			{ name: 'description', type: 'text', default: 'Thursday · ENG2 102' },
			{ name: 'withAction', type: 'boolean', default: true },
			{ name: 'withFooter', type: 'boolean', default: true },
		],
	},
	{
		slug: 'ui/input',
		name: 'Input',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/input',
		controls: [
			{ name: 'placeholder', type: 'text', default: 'you@knights.ucf.edu' },
			{ name: 'disabled', type: 'boolean', default: false },
			{ name: 'invalid', type: 'boolean', default: false },
		],
	},
	{
		slug: 'ui/label',
		name: 'Label',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/label',
		notes: 'Never imported by the app today.',
	},
	{
		slug: 'ui/field',
		name: 'Field',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/field',
		notes: 'Form scaffolding. Used on /settings and /auth/register.',
		controls: [{ name: 'invalid', type: 'boolean', default: false }],
	},
	{
		slug: 'ui/select',
		name: 'Select',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/select',
	},
	{
		slug: 'ui/accordion',
		name: 'Accordion',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/accordion',
		notes: 'Used on /about (about-IEEE section).',
	},
	{
		slug: 'ui/tooltip',
		name: 'Tooltip',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/tooltip',
		notes: 'Never imported by the app today.',
	},
	{
		slug: 'ui/hover-card',
		name: 'HoverCard',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/hover-card',
		notes: 'Never imported by the app today.',
	},
	{
		slug: 'ui/separator',
		name: 'Separator',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/separator',
		notes: 'Never imported by the app today.',
	},
	{
		slug: 'ui/sheet',
		name: 'Sheet',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/sheet',
		notes: 'Never imported — the app hand-rolls fixed-inset modals instead.',
	},
	{
		slug: 'ui/scroll-area',
		name: 'ScrollArea',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/scroll-area',
	},
	{
		slug: 'ui/navigation-menu',
		name: 'NavigationMenu',
		group: 'ui',
		status: 'legacy',
		source: '@watts/ui/navigation-menu',
		notes: 'Used only by components/avatarmenu.tsx — see layout/avatar-menu.',
	},
	{
		slug: 'ui/carousel',
		name: 'Carousel',
		group: 'ui',
		status: 'legacy',
		source: '@watts/ui/carousel',
		notes: 'Used on the home page and /sponsorships; needs real slides.',
	},
	{
		slug: 'ui/chart',
		name: 'Chart',
		group: 'ui',
		status: 'legacy',
		source: '@watts/ui/chart',
		notes: 'Recharts wrapper. Never imported by the app.',
	},
	{
		slug: 'ui/table',
		name: 'Table',
		group: 'ui',
		status: 'ok',
		source: '@watts/ui/table',
		notes: 'Consolidates 3 previously independent hand-rolled admin tables (event-manager, members-manager, resume-dashboard).',
	},
	{
		slug: 'ui/sidebar',
		name: 'Sidebar',
		group: 'ui',
		status: 'legacy',
		source: '@watts/ui/sidebar',
		notes: 'Large shadcn sidebar. Only SidebarProvider is used today (a blur overlay on /projects). Intended home: the dashboard layout.',
	},

	// ---- app components ----------------------------------------------------
	{
		slug: 'layout/navbar',
		name: 'Navbar',
		group: 'layout',
		status: 'legacy',
		source: '@/components/navbar',
		surface: 'marketing',
		notes: '328 LoC, hardcoded link arrays, sm–lg breakpoint gap, dead CONNECT branch. Rebuild target in the shared-layout PR. Auth cluster needs a session.',
	},
	{
		slug: 'layout/footer',
		name: 'Footer',
		group: 'layout',
		status: 'ok',
		source: '@/components/footer',
		surface: 'marketing',
		notes: '"i stole the component… will edit later". Rebuild target.',
	},
	{
		slug: 'layout/avatar-menu',
		name: 'AvatarMenu',
		group: 'layout',
		status: 'ok',
		source: '@/components/avatarmenu',
		surface: 'marketing',
		controls: [{ name: 'image', type: 'text', default: '' }],
	},
	{
		slug: 'layout/dashboard-shell',
		name: 'DashboardShell',
		group: 'layout',
		status: 'ok',
		source: '@/components/shell/dashboard-shell',
		notes: 'Shared sidebar + topbar for /dashboard, /staff and every /admin/* page — replaces each page mounting its own Navbar. Renders full-viewport (fixed sidebar), like the real thing. This preview passes mock auth via DashboardShellView; the real DashboardShell wraps it with a live auth.getAuthStatus query.',
		controls: [
			{ name: 'isAdmin', type: 'boolean', default: true },
			{ name: 'isOfficer', type: 'boolean', default: true },
			{
				name: 'pathname',
				type: 'select',
				options: [
					'/dashboard',
					'/settings',
					'/staff',
					'/admin/dashboard',
					'/admin/members',
					'/admin/events',
					'/admin/photos',
					'/admin/resumes',
				],
				default: '/admin/events',
			},
		],
	},
	{
		slug: 'marketing/signin-block',
		name: 'Signinblock',
		group: 'marketing',
		status: 'ok',
		source: '@/components/signin',
		surface: 'marketing',
	},
	{
		slug: 'marketing/timer',
		name: 'Timer (GBM countdown)',
		group: 'marketing',
		status: 'ok',
		source: '@/components/timer',
		surface: 'marketing',
	},
	{
		slug: 'marketing/calendar',
		name: 'Calendar embed',
		group: 'marketing',
		status: 'ok',
		source: '@/components/calendar',
		surface: 'marketing',
		controls: [{ name: 'className', type: 'text', default: 'h-96 w-full' }],
	},
	{
		slug: 'marketing/about-ieee',
		name: 'AboutIEEE section',
		group: 'marketing',
		status: 'ok',
		source: '@/components/pg/aboutieee',
		surface: 'marketing',
	},
	{
		slug: 'marketing/about-header',
		name: 'AboutHeader hero',
		group: 'marketing',
		status: 'ok',
		source: '@/components/pg/aboutheader',
		surface: 'marketing',
	},
	{
		slug: 'staff/staff-hub',
		name: 'StaffHub',
		group: 'staff',
		status: 'legacy',
		source: '@/components/staff/staff-hub',
		notes: 'Capability-gated staff landing. Needs a staff session to show anything.',
	},
	{
		slug: 'dashboard/event-list',
		name: 'EventList',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/event-list',
		notes: 'Imported by /admin/dashboard and /test/demos — /dashboard now uses the richer dashboard/event-showcase instead.',
	},
	{
		slug: 'dashboard/event-showcase',
		name: 'EventShowcase',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/event-showcase',
		notes: "The member dashboard's event feed — flyer, description, and date/place icons like the marketing site's featured-event panel (pg/eventsidebar.tsx), with an Upcoming/Past toggle. event.getAll is public, so this renders real data with no session.",
	},
	{
		slug: 'dashboard/membership-status',
		name: 'MembershipStatus',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/membership-status',
		notes: 'Dues/officer/member-since. Takes props directly (no query) — the real getMyDashboard-backed version is DashboardWidgets.',
		controls: [
			{ name: 'duesPaid', type: 'boolean', default: true },
			{ name: 'officerStatus', type: 'boolean', default: true },
			{ name: 'officerRole', type: 'text', default: 'Corporate Relations chair' },
			{ name: 'memberSince', type: 'text', default: 'Aug 2024' },
		],
	},
	{
		slug: 'dashboard/committees-projects',
		name: 'CommitteesProjects',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/committees-projects',
		notes: 'Org-badge row. Renders nothing if both arrays are empty — try clearing the controls to see that state.',
	},
	{
		slug: 'dashboard/attendance-summary',
		name: 'AttendanceSummary',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/attendance-summary',
		notes: '6-month bar chart, bucketed client-side from a fixed mock attendance list.',
	},
	{
		slug: 'dashboard/resume-status',
		name: 'ResumeStatus',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/resume-status',
		notes: "Renders nothing if there is nothing on file and upload is not open to this viewer (RESUME_UPLOAD_AUDIENCE) — matches ResumeUpload's own gate on /settings.",
		controls: [
			{ name: 'uploaded', type: 'boolean', default: true },
			{ name: 'canUpload', type: 'boolean', default: true },
		],
	},
	{
		slug: 'dashboard/onboarding-checklist',
		name: 'OnboardingChecklist',
		group: 'dashboard',
		status: 'ok',
		source: '@/components/dashboard/onboarding-checklist',
		notes: "Up to six real column checks — the résumé item only appears if it's reachable (canUploadResume, or already uploaded). Renders nothing once every applicable item is true.",
		controls: [
			{ name: 'discordLinked', type: 'boolean', default: true },
			{ name: 'ieeeNumber', type: 'boolean', default: false },
			{ name: 'knightConnect', type: 'boolean', default: false },
			{ name: 'resume', type: 'boolean', default: true },
			{ name: 'canUploadResume', type: 'boolean', default: true },
			{ name: 'personalDetails', type: 'boolean', default: false },
			{ name: 'hasOrg', type: 'boolean', default: false },
		],
	},
	{
		slug: 'admin/overview',
		name: 'AdminOverview',
		group: 'admin',
		status: 'legacy',
		source: '@/components/admin/overview',
		notes: 'Nine KPIs across member.getOrgStats + event/officer/committee/project queries — all admin-gated, needs a real admin session.',
	},
	{
		slug: 'staff/committees-projects-panel',
		name: 'CommitteesProjectsPanel',
		group: 'staff',
		status: 'legacy',
		source: '@/components/staff/committees-projects-panel',
		notes: 'Rough committee/project membership assignment. Needs an officer/admin session.',
	},
	{
		slug: 'dashboard/member-qr-code',
		name: 'Member_QR_Code',
		group: 'dashboard',
		status: 'legacy',
		source: '@/components/dashboard/member-qr-code',
		notes: 'Check-in pass redesign — ribbon header, name/major, viewfinder-framed QR (components/qr/member-qr-code.tsx\'s new "bare" variant). Needs a real session for the name and QR payload; shows its error state here.',
	},
	{
		slug: 'admin/event-manager',
		name: 'EventManager',
		group: 'admin',
		status: 'legacy',
		source: '@/components/admin/event-manager',
		notes: 'Needs manage_events + real event data. Table structure now shared via @watts/ui/table (dashboard consolidation pass).',
	},
	{
		slug: 'admin/members-manager',
		name: 'MembersManager',
		group: 'admin',
		status: 'legacy',
		source: '@/components/admin/members-manager',
		notes: 'Needs an admin/officer session + member data. Table + toggles now shared (dashboard consolidation pass).',
	},
	{
		slug: 'admin/resume-dashboard',
		name: 'ResumeDashboard',
		group: 'admin',
		status: 'legacy',
		source: '@/components/admin/resume-dashboard',
		notes: 'Needs review_resumes + résumé data. Table structure now shared (dashboard consolidation pass).',
	},
	{
		slug: 'admin/toggle-pill',
		name: 'TogglePill',
		group: 'admin',
		status: 'ok',
		source: '@/components/ui/toggle-pill',
		notes: 'Consolidates 5 previously independent toggle-button implementations across members-manager, resume-filter-bar, and event-manager (dashboard consolidation pass).',
		controls: [
			{ name: 'children', type: 'text', default: 'Toggle' },
			{ name: 'selected', type: 'boolean', default: false },
			{
				name: 'tone',
				type: 'select',
				options: ['brand', 'brand-outline', 'info', 'success'],
				default: 'brand',
			},
			{ name: 'size', type: 'select', options: ['sm', 'xs', 'pill'], default: 'sm' },
		],
	},
];

export function getMeta(slug: string): EntryMeta | undefined {
	return entriesMeta.find((e) => e.slug === slug);
}

export function groupedMeta(): { group: GalleryGroup; entries: EntryMeta[] }[] {
	const groups = new Map<GalleryGroup, EntryMeta[]>();
	for (const e of entriesMeta) {
		const list = groups.get(e.group) ?? [];
		list.push(e);
		groups.set(e.group, list);
	}
	return [...groups.entries()].map(([group, entries]) => ({ group, entries }));
}
