// The WATTS house style. Ported verbatim from apps/ieeeucfcom/eslint.config.mjs so the
// website's lint output is unchanged by the extraction. `ignores` and `tsconfigRootDir`
// stay in each package's own eslint.config.mjs — they are path-relative to the consumer.

/** @type {import('eslint').Linter.RulesRecord} */
export const houseRules = {
	'arrow-spacing': ['warn', { before: true, after: true }],
	'brace-style': ['error', '1tbs', { allowSingleLine: true }],
	'comma-dangle': ['error', 'always-multiline'],
	'comma-spacing': 'error',
	'comma-style': 'error',
	curly: ['error', 'multi-line', 'consistent'],
	'dot-location': ['error', 'property'],
	'handle-callback-err': 'off',
	indent: ['error', 'tab', { SwitchCase: 1 }],
	'keyword-spacing': 'error',
	'max-nested-callbacks': ['error', { max: 4 }],
	'max-statements-per-line': ['error', { max: 2 }],
	'no-console': 'off',
	'no-empty-function': ['error', { allow: ['arrowFunctions'] }],
	'no-floating-decimal': 'error',
	'no-lonely-if': 'error',
	'no-mixed-spaces-and-tabs': 'warn',
	'no-multi-spaces': 'error',
	'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1, maxBOF: 0 }],
	'no-shadow': ['warn', { allow: ['err', 'resolve', 'reject'] }],
	'no-trailing-spaces': ['error'],
	'no-unused-vars': ['off', { varsIgnorePattern: 'path' }],
	'@typescript-eslint/no-explicit-any': 'off',
	'@typescript-eslint/no-inferrable-types': 'off',
	'@typescript-eslint/no-unused-vars': [
		'error',
		{ argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
	],
	'@typescript-eslint/prefer-optional-chain': 'error',
	'@typescript-eslint/no-floating-promises': 'warn',
	'@typescript-eslint/await-thenable': 'error',
	'no-useless-escape': 'off',
	'no-undef': 'off',
	'no-var': 'error',
	'no-return-await': 'error',
	'no-throw-literal': 'error',
	'prefer-promise-reject-errors': 'error',
	'require-await': 'warn',
	'object-curly-spacing': ['error', 'always'],
	'prefer-const': 'error',
	semi: ['error', 'always'],
	'space-before-blocks': 'error',
	'space-before-function-paren': [
		'error',
		{ anonymous: 'never', named: 'never', asyncArrow: 'always' },
	],
	'space-in-parens': 'error',
	'space-infix-ops': 'error',
	'space-unary-ops': 'error',
	'spaced-comment': 'error',
	yoda: 'error',
};
